### ISSUE TITLE
update ROM bank table

### ISSUE THREAD

**Issue by irmen** [commanderx16/x16-docs#107]
https://github.com/commanderx16/x16-docs/blob/master/X16%20Reference%20-%2007%20-%20Memory%20Map.md#rom-allocations

Since https://github.com/commanderx16/x16-rom/pull/334  got merged the table is now incomplete

**Comment by Frosty-J** [comment]
Anyone looking to update this should remember to change the "[Currently unused]" section, since the table saying banks 6-31 are unused contradicts 6 and 7 being used for CHARSET and CODEX.
