### ISSUE TITLE
The examples for VPEEK and VPOKE are wrong...

### ISSUE THREAD

**Issue by EgonOlsen71** [commanderx16/x16-docs#2]
...because they are using PEEK and POKE instead of the V... variants.

While we are talking about VPOKE and VPEEK...I assume they do some bank switching, execute and then switch back? Or what are they actually doing (and how?)?

I'm preparing my BASIC compiler to support them, which works so far but I've no idea what to do with the "bank" parameter. Currently, I'm just writing it into address 2 as some placeholder code, but I would like to know what would be actually the right thing to do with it?

**Comment by mist64** [comment]
https://github.com/commanderx16/x16-rom/blob/master/basic/x16additions.s#L64
