### ISSUE TITLE
Errors in documentation for GETJOY

### ISSUE THREAD

**Issue by joolin1** [commanderx16/x16-docs#23]
The documentation says: "The routine GETJOY retrieves all state from the two joysticks and stores it in the memory locations JOY1 ($02BC-$02BE) and JOY2 ($02BF-$02C1)." It is wrong. The addresses are $00EF-$00F1 and $00F2-$00F4.

The bits for up, down, left, right is in a different order than the documentation says. The right order is:
bit 3 - down
bit  2 - up
bit 1 - right
bit 0 - left

**Comment by mist64** [comment]
The addresses are correct for the current version of the ROM in the repository. The last release still has the old addresses.

What is your bit ordering based on? Based on the keyboard in the emulator? A gamepad in the emulator? A gamepad on real hardware? The documentation is correct, but maybe the implementation isn't.

**Comment by joolin1** [comment]
I am using the emulator without any controllers so the state of the keyboard is returned when I call GETJOY. When I tested the bits in address $00EF I realized the order was different.

**Comment by joolin1** [comment]
I just realized it's my mistake. I had a bug in my assembly code. I am sorry, I just wanted to help. Thanks for all your work with the emulator. I am very glad for this project!

**Comment by indigodarkwolf** [comment]
Sounds like this can be closed, then.

**Comment by oziphantom** [comment]
> Description: The routine GETJOY retrieves all state from the two joysticks and stores it in the memory locations JOY1 ($02BB-$02BD) and JOY2 ($02BE-$02C0).

I just lost 2 hours to this.. JOY1 is $02B**C**-$02B**E** and JOY2 is $02B**F**-$02C**0**
