### ISSUE TITLE
Questions about the documentation on VERA

### ISSUE THREAD

**Issue by lgblgblgb** [commanderx16/x16-docs#4]
I have some issues to understanding VERA documentation (0.8 now):

* minor typos in internal address space: at palette and sprite data, the range is invalid (end address is less than start address). OK, fair enough, it should be some typo only, or left from the previous version this way.
* BM_PALETTE_OFFSET is never explained what it does (simply add the value to palette offset? or it is interpreted as the high nybble to form the palette index?), even at the first occurrence: "in the same way as in the tile modes ..." but it's at the tile modes, so kind of recursive reference :) Also it looks like problematic, as tile modes does not even have palette_offset, as it states that L1/L2 regs for BM_PALETTE_MODE only applies to bitmap modes, not for tiles and/or text?
* is TILEW and TILEH applied to text modes as well? Would be funny to be able to use 8x8, 16x8, 8x16 and 16x16 fonts as well, but maybe that is in contrast with the statement that text modes must be 8x8. So I am not sure what should be believed.
* sprite X and Y coordinates are independent of anything, like border bounaries (ie h/v start is non-zero ...), scaling (of L1/L2 layer) etc?
* minor interpretation difficulties with mode 0/1, in one table is told to be tile 1bpp for each basically, then description mentions those are text modes, with always 8x8 as the character set. Maybe the same question from me, as one above ... Yes, I understand that text mode is basically a tile mode in nature, however it's not clear how different from the "other" tile modes ...
* it would be nice to have some description how VERA reacts to register modifications, like: is it possible to change mode even within a scanline, or applies to the next scanline, or even it waits for the tile height to be finished first, etc etc.
* Also for some question: no PAL composite/RGB/whatever, just NTSC? :( Living in Europe, everything I have is PAL (and probably it's true for many other people as well, not just me) ... Surely it's not so much a question with VGA output :) but otherwise, for some retro experience, it can be a problem with CRTs etc ... After as we all know NTSC means NeverTheSameColour [it meant to be a joke, sorry ...] compared to PAL :) Ok, forget it, if it sounded too 'rude' or anything like that.

Sorry for my probably misunderstandings here, maybe my limited English knowledge (also can be seen above ... how I wrote this issue) is the problem that I didn't catch all the important points already written somewhere. And yeah, sorry about the NTSC joke :-O

**Comment by lgblgblgb** [comment]
Sorry, it seems palette offset at least described at some place, what I've missed :-O

**Comment by fvdhoef** [comment]
I agree, the documentation needs some work. To comment on some of your questions:
- The layer modes 0/1 support all tile sizes. For example, you can upload a VGA 8x16 font and have a 80x30 mode. The main difference between mode 0/1 and the other tile modes is the format of the upper byte (color directly specified in tile map in mode 0/1).
- All scaling and borders are performed on the full screen (after compositing) at the moment. This may still change in a future version.
- It is true that PAL isn't supported. This is mostly a design decision because it would add a 50Hz mode to the system, whereas NTSC and VGA are both 60Hz. I have considered a 60Hz PAL mode, but since the system also has a RGB mode, it is better in europe to just use a SCART cable to have the best 15kHz display possible.

**Comment by lgblgblgb** [comment]
Thanks for your answer! Ah yes, I thought that 50Hz will be the problem :) It's always goes that way, in other projects as well, it seems. I just wondering if it's possible to add DMA like commands for VERA, so it can execute blazing fast VRAM operations (especially for modulo / transparent supported copy operations maybe with fractional step support) without the CPU involved at all (though probably, the CPU should stop uses the data ports till that maybe a busy flag or so to indicate that?). Then one can happily say that no need for a memory-mapped shared video RAM solution too much for almost anything :) OK, as usual, I'm too keen not to go off-topic, sorry ...

**Comment by m00dawg** [comment]
Are the registers for the external address space correct? The docs show:

0 VERA_ADDR_LO
2 VERA_ADDR_MID
1 VERA_ADDR_HI

But the vera.inc that is in the example files defines it as:

1 VERA_ADDR_LO
2 VERA_ADDR_MID
3 VERA_ADDR_HI

Not sure which is which?

**Comment by indigodarkwolf** [comment]
@m00dawg The Vera 0.8 docs have been released ahead of the version of the emulator that actually uses them.

If you're using emulator release r30, then:
* $9F20 is VERA_ADDR_HI
* $9F21 is VERA_ADDR_MID
* $9F22 is VERA_ADDR_LO

However, if you've built the emulator from the latest code in the repositories, then:
* $9F20 is VERA_ADDR_LO
* $9F21 is VERA_ADDR_MID
* $9F22 is VERA_ADDR_HI

I assume r31, whenever it is released, will be running on Vera 0.8 and folks will need to follow that documentation.

**Comment by m00dawg** [comment]
Ah ok thanks, that helps!

This is what I have then in my include:
`.const VERAREG   = $9f20
// Note the doc (0.8) has MID and HI reversed?
// Not sure which is right
.const VERALO    = VERAREG + 0
.const VERAMID   = VERAREG + 1
.const VERAHI    = VERAREG + 2
.const VERADAT   = VERAREG + 3
.const VERADAT2  = VERAREG + 4
.const VERACTL   = VERAREG + 5
.const VERAIEN   = VERAREG + 6
.const VERAISR   = VERAREG + 7
`

**Comment by indigodarkwolf** [comment]
What you may want to do, depending on your assembler's feature-set, is define a value to switch between Vera 0.7 mappings (for development on r30) and Vera 0.8 mappings (to make it easier to swap to Vera 0.8 soon-ish).

I can only show how that would work on ACME:
```asm
!set VERA_0_8 = 0
!if VERA_0_8 == 1 {
    VERAHI = VERAREG + 0
    VERAMID = VERAREG + 1
    VERALO = VERAREG + 2
} else {
    VERALO = VERAREG + 0
    VERAMID = VERAREG + 1
    VERAHI = VERAREG + 2
}
```
...amongst several other differences.

**Comment by m00dawg** [comment]
Ah that's a good call yep! I'm using Kick-Assembler for the moment. Still learning the ins and out of it. Pretty sure I can do like the above, but haven't figured out how yet.

**Comment by mist64** [comment]
The VERA reference is now open source and available as a Markdown file in this repository. If you have fixes or suggestions, you can open full requests. :)

**Comment by lgblgblgb** [comment]
Will PS/2 handing be "ported" to VERA as well? I mean, basically it's a serial protocol, kinda like SPI, with clock signal, though not the same. I have no idea how it works NOW, but AFAIK it's connected to a VIA and must to deal with it (?) in software. I guess it's not so nice, as it takes CPU power. No problem when computer waits for input, surely, but for a game, also just checking some key is pressed, it can be a problem ... For me, it looks like SPI (again: surely it is NOT SPI, just a bit similar), so just a shift register is implemented basically, IIRC PS/2 CLK is generated by the keyboard, so here the master (???) is mostly the kbd, the opposite as with SD-card with SPI protocol.

My other question if it's planned to have more SPI select lines, maybe to drive "user expansion" with SPI stuffs, there are tons of modern stuff can be accessed via either SPI or I2C which would be kinda easy than to hook on X16 without too much extra effort to build a logic to interface with a parallel CPU bus on the expansion port, or such ...

**Comment by fvdhoef** [comment]
Not at this time. The FPGA is completely out of free pins. Maybe in the phase2 or 3 X16 board, there we will probably switch to a bigger FPGA.

**Comment by lgblgblgb** [comment]
Understand. i see the "danger" (danger in the sense that not everybody like that happening) too much things go into the FPGA, but frankly ... Almost every 8 bit systems back in their they already used custom chips even for memory banking whatever, and without mass production, custom chips would be killer priced, so it "must" be FPGA, CPLD (for simplier cases etc). As far as I see, X16's choice for memory banking is also effected by the fact that it must be simple enough not require too much components to realize, though it can be more sophisticated with that (ie many cases the fixed KERNAL is a waste and better to be switchable, etc). Interesting paradigm :-O But everything can be made as complicated as desired and requires more time to sort out problems and more hardware to implement then, or more (bigger) FPGA :) Ok, thanks for your time for answered my "curiosity" kind of questions though!!!

**Comment by indigodarkwolf** [comment]
Are there any outstanding issues in this issue? I think they've all been addressed in one way or another. Should this be closed?

**Comment by lgblgblgb** [comment]
I guess so. Just I am not sure if I should close it, or it's more the task of the X16 "team members" :)
