### ISSUE TITLE
$030C-$030F not populated by SYS?  [r37]

### ISSUE THREAD

**Issue by bobbyjim** [commanderx16/x16-docs#44]
I'm running r37.

From the monitor, I can enter "G FF9C" or "G FF99" and I can see that MEMTOP is $0800 and MEMBOT is $9F00.

However, when I run SYS $FF9C from BASIC, the pseudo-registers at #780-#783 do not appear to be populated.  I guess this is something missing from SYS, or perhaps those values are being stored elsewhere on the X16?

**Comment by indigodarkwolf** [comment]
Well, I think you mean the pseudo-registers at $030C-$030F (which are memory addresses 780-783 -- dollar sign notation is for hexadecimal numbers). Regardless, I'm seeing the same thing, BASIC doesn't seem to write the contents of the A, X, and Y registers there, or anywhere.

**Comment by greg-king5** [comment]
It works for me.
```BASIC
POKE $30F,1:SYS $FF99:PRINT $9F;PEEK($30E);PEEK($30D)
 159  159  0
```

**Comment by indigodarkwolf** [comment]
That populates the memory. Is $030F loaded into the carry bit of the processor?

**Comment by greg-king5** [comment]
> That populates the memory. Is $030F loaded into the carry bit of the processor?

It's pushed onto the stack, then pulled off into the "Processor Status Word" (the official name of the flags register).  After the `SYS`, the PSW is pushed onto the stack; then pulled off, and stored in $030F.  (Bits four and five always contain ones.)

Be careful of what you poke there -- you usually don't want to disable interrupts!

**Comment by bobbyjim** [comment]
I found this when I was writing a little BASIC to create a primitive "memory map" dynamically.  (You know, so it's safe from changes:)

**Comment by irmen** [comment]
@bobbyjim this issue can be closed I think because it seems to work?
