### ISSUE TITLE
Example showing the character ROM in the video controller doesn't work

### ISSUE THREAD

**Issue by mobluse** [commanderx16/x16-docs#6]
Unfortunately this example in https://github.com/commanderx16/x16-docs/blob/master/Programmer's%20Reference%20Guide.md doesn't seem to work. It should print the first two PETSCII characters, right? Maybe the character set has moved. How can one get the address of the character set oneself? I tried, but couldn't read Layer 1 registers to get TILE_BASE.

> The `OV` command takes a 4 bit hex value as an argument and sets it as the bank in the video address space for reading and writing memory contents. The following example shows the character ROM in the video controller's address space:
> 
> ```
> OV2
> EC0000 000F
> ```

Now it prints:
```
.
.[0000 *.*.....        
.[0001 ........        
.[0002 ********        
.[0003 ********        
.[0004 ********        
.[0005 ********        
.[0006 ********        
.[0007 ********        
.[0008 ********        
.[0009 ********        
.[000A ********        
.[000B ********        
.[000C ********        
.[000D ********        
.[000E ********        
.[000F *.......
```

**Comment by mist64** [comment]
Documentation fix (VERA 0.8 change): 8a20f96

ROM fix: https://github.com/commanderx16/x16-rom/commit/3d0d016462156bbf8e3a1ce6569d6bd2b14f51da
