### ISSUE TITLE
Document Math library

### ISSUE THREAD

**Issue by mist64** [commanderx16/x16-docs#68]
The Microsoft BASIC math library has been separated out into its own component, and has a dedicated jump table – similar to the C128/C65. It needs to be documented.

These can probably used as templates:
* [C128_Developers_Package_for_Commodore_6502_Development_(1987_Oct).pdf](http://www.zimmers.net/anonftp/pub/cbm/schematics/computers/c128/servicemanuals/C128_Developers_Package_for_Commodore_6502_Development_(1987_Oct).pdf) (chapter 13)
* http://www.zimmers.net/anonftp/pub/cbm/manuals/c65/c65manualupdated.txt

See also https://github.com/commanderx16/x16-rom/issues/231

**Comment by irmen** [comment]
How extensive do we expect to have this documented? Those references are very specific! (well, the second one at least. Somehow the first one won't download for me)
The  jump table is already in the programmer's reference document

**Comment by indigodarkwolf** [comment]
I would say... it's difficult to say. It's some function of Michael's time and motivation, my time and motivation, or the time and motivation of any third party who submits a pull request before we get to it. 😃

**Comment by mist64** [comment]
It may be as easy as copying over the C128 or C65 reference, in case we're compatible (which is the goal).

**Comment by irmen** [comment]
Yeah I forgot about the table of functions in the reference documentation as well, it looks to be the r39 version as well.
If we make a new document for the math package, I imagine it can be removed from the reference doc again
