### ISSUE TITLE
Typo in Vera 0.8 in the table "Internal Address Space"

### ISSUE THREAD

**Issue by indigodarkwolf** [commanderx16/x16-docs#7]
$F1000-$F01FF | Palette

should read:

$F1000-$F11FF | Palette

**Comment by greg-king5** [comment]
The end-address for "Sprite data", also, is wrong.

**Comment by lgblgblgb** [comment]
Indeed, I asked those too in #4

**Comment by mist64** [comment]
Fixed in new Markdown document.
