### ISSUE TITLE
SCREEN mode differences

### ISSUE THREAD

**Issue by tseemann** [commanderx16/x16-docs#77]
https://github.com/commanderx16/x16-docs/blob/c71f3cd99b6149a846c9a58a18c9f1ef961e0336/X16%20Reference%20-%2003%20-%20BASIC.md?plain=1#L344-L346

`SCREEN 3` gives `ILLEGAL QUANITY` error now.
I think I saw a commit with new mode numbers?

**Comment by mist64** [comment]
Works for me. Did you test it with r39?

**Comment by tseemann** [comment]
Michael,

It turns out I was using r38 and not r39...
I missed the new release.
This explains the differences in documentation.
I apologise for this silly mistake!

However, I am using the r39 mac ZIP download!

```
% md5 x16emu_mac-r39.zip
MD5 (x16emu_mac-r39.zip) = 96803ffa552de143489a1c12317eaa48

% unzip x16emu_mac-r39.zip

% x16emu -version
### Release 38 ("Kyoto")
```

But the boot screen shows R39 and `SCREEN 3` now works.

**Comment by tseemann** [comment]
Oh i think you may have fixed this since r39 was released?

https://github.com/commanderx16/x16-emulator/commit/2c799f51c094bc088bc4f31b704aee0c425a7f8e

**Comment by mist64** [comment]
Yes, r39 in fact identified itself as r38 on the command line. :(
But the included ROM printed the correct version.
