### ISSUE TITLE
LOCATE example syntax error

### ISSUE THREAD

**Issue by tseemann** [commanderx16/x16-docs#78]
https://github.com/commanderx16/x16-docs/blob/c71f3cd99b6149a846c9a58a18c9f1ef961e0336/X16%20Reference%20-%2003%20-%20BASIC.md?plain=1#L209-L218

This gives `SYNTAX ERROR LINE 180` now.

In the HTML version included in the emulator, the `LOCATE` keyword doesn't seem to be documented. Has it been removed?

**Comment by mist64** [comment]
Works for me. Did you test it with r39?

**Comment by tseemann** [comment]
Works on R39, sorry for missing the update.
